version: "3.2"
services:

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"

  postgres:
    image: postgres:13.3
    depends_on:
      - redis
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5432:5432"
